### ISSUE TITLE
(Easy) Change a successful refresh call to be when the status code is < 300 as opposed to === 200

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-android#4]
In [this](https://github.com/supertokens/supertokens-android/blob/master/app/src/main/java/io/supertokens/session/SuperTokensInterceptor.java#L190) and [this](https://github.com/supertokens/supertokens-android/blob/master/app/src/main/java/io/supertokens/session/SuperTokensHttpURLConnection.java#L183) function, we need to change `!= 200` to ` >= 300`

**Comment by UbadahJ** [comment]
Can I take this issue? Also, I have reviewed the repo and should all the associated tests and CL/CI files be changed as well?

**Comment by UbadahJ** [comment]
@rishabhpoddar What about the test cases?

**Comment by UbadahJ** [comment]
1. My OS is 

```bash
$ uname -a
Linux one 5.8.12-arch1-1 #1 SMP PREEMPT Sat, 26 Sep 2020 21:42:58 +0000 x86_64 GNU/Linux
```

2. As for the guide, I only followed the guide from the android repo, so I will check the core and will get back to you

**Comment by rishabhpoddar** [comment]
@UbadahJ it can be slightly challenging to setup the dev env completely. So you may wanna join our [discord](https://supertokens.io/discord) to ask questions or see the contributing channel for questions from someone who tried to set it up recently, in case you run into the same issues.

Thanks!

**Comment by UbadahJ** [comment]
@rishabhpoddar Thank you for the detailed info; From your second point, I re-read the contribution guide and seems like I need to skip steps 1 and 4 in the core guide, not in the android guide :facepalm:. Anyways I got it and on the final stages of setting up. If I had any more questions will check out discord. 

Also, the third point was also valid since I was using fish and the script was not executing correctly.

**Comment by rishabhpoddar** [comment]
Fair enough!! I guess we should make the skipping of steps 1 & 4 MUCH BIGGER!

**Comment by UbadahJ** [comment]
Maybe explicitly stating skipping the steps in the core guide for people like me would be an immense help

@rishabhpoddar Also, is MacOS the reason there is no shebang with bash/sh at the starting of scripts?

**Comment by rishabhpoddar** [comment]
> Maybe explicitly stating skipping the steps in the core guide for people like me would be an immense help

Sounds good!

> Also, is MacOS the reason there is no shebang with bash/sh at the starting of scripts?

Not really. I had forgotten to add it to that script. That's all

**Comment by UbadahJ** [comment]
There was not one in `supertokens-android/setup-pre-commit.sh` and `supertokens-root/startTestingEnv`.

**Comment by rishabhpoddar** [comment]
Thanks! Have added `#!/bin/bash` to those scripts
