### ISSUE TITLE
doesSessionExist

### ISSUE THREAD

**Issue by dreuff** [supertokens/supertokens-android#64]
Hello,
I'm using OkHttp3/Retrofit.
About 20 minutes after sign in, `doesSessionExist` return false.
Is it the same issue as https://github.com/supertokens/supertokens-android/issues/33#issue-1334916673 ?

**Comment by nkshah2** [comment]
Hi @dreuff 

The issue you linked to is related to sign out not clearing cookies. In your case does it consistently return false after 20 minutes or so?

If yes can you share:
- The config on the frontend when initialising SuperTokens
- The config on the backend when initialising SuperTokens
- If you have modified or adjusted the values of the config in the core instance, please tell us what config properties you adjusted and what values you set for them

Can you also check if the refresh token endpoint is called on your backend when doesSessionExist returns false, if yes what was the status code you got back from the endpoint

**Comment by dreuff** [comment]
Hello,
At launch of my app, when I call  `doesSessionExist` twice, it returns false the first time and true the second..
My config is basic.
I didn't check if the refresh token endpoint is called, but now I don't need `doesSessionExist` anymore since I have to handle offline mode, so I call my API and check if the code response is 401 to check if the user is logged in.

**Comment by nkshah2** [comment]
@dreuff 

Please share the config you are using on the frontend and backend. I can debug further from there

**Comment by nkshah2** [comment]
Closing this issue for now, if you face this issue again feel free to reopen
